# Generated by Django 4.2 on 2026-06-25 20:21

from django.db import migrations, models

import dashboard.models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_learningmaterial"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningmaterial",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Upload a PDF, JPG, or PNG file",
                null=True,
                upload_to=dashboard.models.learning_material_upload_path,
                verbose_name="File",
            ),
        ),
    ]
